### DISCUSSION TITLE
What am I doing wrong?

### DISCUSSION THREAD

**Discussion by amaximus** [elchininet/home-assistant-secret-taps#7] [General]
Hi,

I'm trying to achieve the following goal:
on any tap on the UI the brightness of the tablet (where the UI runs with user Csalad logged in) should be increased and after a timeout decreased.
The below script tablet_brightness works otherwise via an automation on state changing taps which I want to give up on if I get the secret taps solution working.

I defined a ${HA_CONF}/www/community/home-assistant-secret-taps/secret_taps.yaml:
```
(ha_venv3_12) pi@raspberrypi:~/homeassistant_conf/www/community/home-assistant-secret-taps $cat secret-taps.yaml
enabled: true
profiles:
  - user:
    - Csalad
    secrets:
      - taps:
        - tap
        action: call-service
        service: script.tablet_brightness
(ha_venv3_12) pi@raspberrypi:~/homeassistant_conf/www/community/home-assistant-secret-taps $cat ../../../scripts.yaml |tail -14
tablet_brightness:
  alias: 'tablet brightness'
  sequence:
    - service: notify.mobile_app_lenovo_tb_8505f
      data:
        message: "command_screen_brightness_level"
        data:
          command: 70
    - delay: 00:00:30
    - service: notify.mobile_app_lenovo_tb_8505f
      data:
        message: "command_screen_brightness_level"
        data:
          command: 7
(ha_venv3_12) pi@raspberrypi:~/homeassistant_conf/www/community/home-assistant-secret-taps $cat ../../../automations/tablet_brightness.yaml
alias: "Tablet brightness"
initial_state: "on"
id: tablet_brightness
mode: restart
trigger:
  platform: event
  event_type: state_changed
  context:
    user_id: fd5915f85579493eb6243c2f038c38cd
action:
  - service: notify.mobile_app_lenovo_tb_8505f
    data:
      message: "command_screen_brightness_level"
      data:
        command: 70
  - delay: 00:00:30
  - service: notify.mobile_app_lenovo_tb_8505f
    data:
      message: "command_screen_brightness_level"
      data:
        command: 7
(ha_venv3_12) pi@raspberrypi:~/homeassistant_conf/www/community/home-assistant-secret-taps $
```

What is wrong with my approach or what did I misunderstand related to secret taps?
Any help would be appreciated.
