### ISSUE TITLE
I can't get this to work

### ISSUE THREAD

**Issue by RedNo7** [elchininet/home-assistant-secret-taps#6]
Firstly I think this is a fantastic idea! 👍 

I cannot, however get it to work.

I've added the repository installed via HACS, add the `extra_module_url`, added `www\secret-taps.yaml`, reset the front-end cache on my iPhone but I cannot get it to work.

Here is my yaml
```yaml
frontend:
  extra_module_url:
    - /hacsfiles/home-assistant-secret-taps/home-assistant-secret-taps-plugin.js?v1.0.1
```

```yaml
enabled: true
profiles:
  - user:
      - James
      - iPad
    secrets:
      - taps:
          - tap
          - double-tap
          - tap
        action: call-service
        service: input_boolean.turn_on
        data:
          entity_id: input_boolean.kiosk_mode
  - admin: true
    secrets:
      - taps:
          - tap
          - double-tap
          - tap
        action: call-service
        service: input_boolean.turn_on
        data:
          entity_id: input_boolean.kiosk_mode
``` 

I've tried variations eg:
```yaml
        action: call-service
        service: input_boolean.turn_on
        data:
          target:
            entity_id: input_boolean.kiosk_mode
```

But it doesn't work.  Is there anything obvious I have got wrong?
